apiVersion: v1
kind: ConfigMap
metadata:
  name: calcom-config
data:
  NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
  NODE_ENV: production
  CALCOM_TELEMETRY_DISABLED: "true"
  NEXT_PUBLIC_LICENSE_CONSENT: "agree"
