apiVersion: v1
kind: Secret
metadata:
  name: calcom-secret
type: Opaque
data:
  password: cm9vdAo=
  username: cm9vdAo=
  database: Y2FsY29tCg==
  host: cG9zdGdyZXM6NTQzMgo=
  port: NTQzMgo=
  url: cG9zdGdyZXNxbDovL3Jvb3Q6cm9vdEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY2FsY29tCg==
  NEXTAUTH_SECRET: S1pObGlQc2hqWm1vS2FlSy9LK0NwdUxaY0FFaWlyZ1MvK2VYdFZjMmRsaz0K
  CALENDSO_ENCRYPTION_KEY: N2E3YjEzOTRkZWE1Yzk4YjBmYjc5MWU0NTZjMTQxNzYK
